# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-31 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190731_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbRating',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
