# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-31 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190731_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
